language: objective-c
before_install:
    - brew update
    - brew install xctool
script: cd objc/VotingInformationProject && xctool -workspace VotingInformationProject.xcworkspace -scheme VotingInformationProject VotingInformationProjectTests
